# Generated by Django 6.0.4 on 2026-04-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibasco_league_app', '0004_topscorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='status',
            field=models.CharField(choices=[('UP', 'Upcoming'), ('LI', 'Live'), ('FT', 'Full Time')], default='UP', max_length=2),
        ),
    ]
