# Generated by Django 6.0.4 on 2026-04-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibasco_league_app', '0005_fixture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='drawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
